#!/usr/bin/env ruby

file 'prefixfree.js', 'https://raw.github.com/LeaVerou/prefixfree/gh-pages/prefixfree.js'
file 'modernizer.js', 'http://modernizr.com/downloads/modernizr-2.5.3.js'
file 'normalize.css', 'https://raw.github.com/necolas/normalize.css/master/normalize.css'
