#!/usr/bin/env ruby

folder 'vendor/assets/javascripts' do
  file 'prefixfree.js', 'https://raw.github.com/LeaVerou/prefixfree/gh-pages/prefixfree.js'
  file 'underscore.js', 'http://underscorejs.org/underscore.js'
  file 'modernizer.js', 'http://modernizr.com/downloads/modernizr-2.5.3.js'
  # jquery mobile
end

folder 'vendor/assets/stylesheets' do
  file 'fontawesome.css.erb', 'https://raw.github.com/FortAwesome/Font-Awesome/master/css/font-awesome.css'
  # jquery mobile
end

folder 'vendor/assets/fonts' do
  base = 'https://github.com/FortAwesome/Font-Awesome/raw/master/font/'
  file 'fontawesome-webfont.woff', base + 'fontawesome-webfont.woff'
  file 'fontawesome-webfont.ttf', base + 'fontawesome-webfont.tff'
  file 'fontawesome-webfont.eot', base + 'fontawesome-webfont.eot'
  file 'fontawesome-webfont.svg', base + 'fontawesome-webfont.svg'
end
